CREATE TABLE addresses
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    street       VARCHAR(30)                             NOT NULL,
    city         VARCHAR(30)                             NOT NULL,
    postal_code  VARCHAR(255)                            NOT NULL,
    country      VARCHAR(30)                             NOT NULL,
    country_code VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_addresses PRIMARY KEY (id)
);

CREATE TABLE customers
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name           VARCHAR(20),
    last_name            VARCHAR(20),
    email                VARCHAR(255),
    phone                VARCHAR(20),
    passport_number      VARCHAR(100)                            NOT NULL,
    emergency_contact_id BIGINT                                  NOT NULL,
    address_id           BIGINT,
    CONSTRAINT pk_customers PRIMARY KEY (id)
);

CREATE TABLE emergency_contacts
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name   VARCHAR(20),
    last_name    VARCHAR(20),
    email        VARCHAR(255),
    phone        VARCHAR(20),
    relationship VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_emergency_contacts PRIMARY KEY (id)
);

CREATE TABLE tour_plan
(
    tourist_sheet_id BIGINT NOT NULL,
    item             VARCHAR(15)
);

CREATE TABLE tourist_sheets
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    travel_start_date date                                      NOT NULL,
    travel_end_date   date                                      NOT NULL,
    flight_details    VARCHAR(100),
    customer_id       BIGINT                                    NOT NULL,
    created_tm        TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    updated_tm        TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    CONSTRAINT pk_tourist_sheets PRIMARY KEY (id)
);

ALTER TABLE addresses
    ADD CONSTRAINT uc_address_street_city UNIQUE (street, city, country);

ALTER TABLE customers
    ADD CONSTRAINT uc_customer_first_name UNIQUE (first_name, last_name, email, phone, passport_number,
                                                  emergency_contact_id);

ALTER TABLE emergency_contacts
    ADD CONSTRAINT uc_emergency_contact UNIQUE (first_name, last_name, email, phone, relationship);

ALTER TABLE tourist_sheets
    ADD CONSTRAINT uc_tourist_sheet_customer_id UNIQUE (customer_id);

ALTER TABLE customers
    ADD CONSTRAINT FK_CUSTOMERS_ON_ADDRESS FOREIGN KEY (address_id) REFERENCES addresses (id);

ALTER TABLE customers
    ADD CONSTRAINT FK_CUSTOMERS_ON_EMERGENCY_CONTACT FOREIGN KEY (emergency_contact_id) REFERENCES emergency_contacts (id);

ALTER TABLE tourist_sheets
    ADD CONSTRAINT FK_TOURIST_SHEETS_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customers (id);

ALTER TABLE tour_plan
    ADD CONSTRAINT fk_tour_plan_on_tourist_sheet FOREIGN KEY (tourist_sheet_id) REFERENCES tourist_sheets (id);